export const bookTitles = [
  "1984",
  "To Kill a Mockingbird",
  "The Great Gatsby",
  "Pride and Prejudice",
  "The Catcher in the Rye",
  "Harry Potter and the Sorcerer's Stone",
  "The Alchemist",
  "The Lord of the Rings",
  "The Hunger Games",
  "The Da Vinci Code",
  "The Alchemist",
  "The Road",
  "Gone Girl",
  "The Girl with the Dragon Tattoo",
  "The Kite Runner",
  "The Fault in Our Stars",
  "The Night Circus",
  "The Book Thief",
  "A Game of Thrones",
  "The Martian",
  "The Catcher in the Rye",
  "The Picture of Dorian Gray",
  "The Adventures of Huckleberry Finn",
  "Moby-Dick",
];
